# Generated by Django 3.2.5 on 2022-06-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peach', '0003_encuesta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='experiencia',
            field=models.IntegerField(),
        ),
    ]
